<?php
include_once CMPD_PLUGIN_DIR . '/backend/classes/SettingsView.php';
$settingsView = new CMPD_SettingsView();

$tabs	 = array(
	'general'		 => 'General',
	'api'			 => 'API',
	'product'		 => 'Product Page',
	'advertisement'	 => 'Advertisement',
	'index'			 => 'Product Directory',
	'appearance'	 => 'Directory Appearance',
	'category_list'	 => 'Category List',
	'custom_css'	 => 'Custom CSS',
	'labels'		 => 'Labels',
);
$tabs	 = apply_filters( 'cmpd_settings_pages', $tabs );

if ( !function_exists( 'cmpd_settings_radio' ) ) {

	function cmpd_settings_radio( $name, $options, $currentValue ) {
		$result = '';
		foreach ( $options as $value => $text ) {
			$result .= sprintf( '<div style="margin-bottom:0.5em;"><input type="radio" name="%s" id="%s_%s" value="%s"%s />'
			. '<label for="%s_%s"> %s</label></div>', $name, $name, $value, $value, ( $currentValue == $value ? ' checked="checked"' : '' ), $name, $value, $text
			);
		}
		return $result;
	}

}
?>
<div class="clear"></div>
<?php do_action( 'CMPD_show_messages' ); ?>
<?php
if ( !empty( $messages ) ):
	foreach ( $messages as $message ):
		?><div class="updated"><p><?php echo $message; ?></p></div><?php
	endforeach;
endif;
?>

<?php
require('settings/top.phtml');
$settingsTabsArrayBase	 = array();
$settingsTabsArray		 = apply_filters( 'cmpd-settings-tabs-array', $settingsTabsArrayBase );
?>

<form method="post" enctype="multipart/form-data" id="cm-product-directory-settings-form">

    <div id="tabs">
        <ul><?php foreach ( $tabs as $id => $name ): ?>
				<li><a href="#tab_<?php echo esc_attr( $id ); ?>"><?php echo $name; ?></a></li>
				<?php
			endforeach;
			if ( !empty( $settingsTabsArray ) ) {
				foreach ( $settingsTabsArray as $id => $name ):
					?>
					<li><a href="#tab_<?php echo esc_attr( $id ); ?>"><?php echo $name; ?></a></li>
					<?php
				endforeach;
			}
			?>

        </ul>


		<?php foreach ( $tabs as $id => $name ): ?>
			<div id="tab_<?php echo esc_attr( $id ); ?>" class="tab-content">
				<?php require('settings/' . $id . '.phtml'); ?>
			</div>
			<?php
		endforeach;

		if ( !empty( $settingsTabsArray ) ) {
			foreach ( $settingsTabsArray as $tabKey => $tabLabel ) {
				$filterName = 'cmpd-custom-settings-tab-content-' . $tabKey;

				echo'<div id="tab_' . $tabKey . '" class="tab-content">';
				echo apply_filters( $filterName, '' );
				echo '</div>';
			}
		}
		?>
    </div>
	<?php
	/* nonce field */
	wp_nonce_field( 'dg@3vasdHHT4$bsdcs_SDdSS34637', 'cmpd_nonce' );
	?>
    <input type="submit" class="cmpd-button button-primary" value="Update" />


</form>
