
<?php if( !ini_get('allow_url_fopen') ): ?>
	<span style="color:red"><?php echo CMA_Settings::__('Your server configuration needs to be changed to allow social login. Please enable allow_url_fopen in your global php.ini file on the server.'); ?></span>
<?php endif; ?>

<h3 class="cm-settings-collapse-btn">
	<span class="dashicons dashicons-arrow-down"></span>
	<strong>Facebook</strong>
</h3>
<p>Instructions are available here: <a href="​http://creativeminds.helpscoutdocs.com/article/988-cm-answers-cma-social-login-facebook">​http://creativeminds.helpscoutdocs.com/article/988-cm-answers-cma-social-login-facebook</a></p>
			<p>Redirect URI: <?php echo site_url(); ?>/auth/facebook/int_callback</p>
<div class="cm-settings-collapse-container cm-settings-collapse-open">
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">App ID:</div>
		<div class="cm-settings-control"><input type="text" name="fb_app_id" value="<?php echo esc_attr($fb_app_id); ?>" /></div>
		<div class="cm-settings-desc">
			<?php echo CMA_Settings::__('Facebook App ID'); ?>
		</div>
	</div>
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">App Secret:</div>
		<div class="cm-settings-control"><input type="text" name="fb_app_secret" value="<?php echo esc_attr($fb_app_secret); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('Facebook App Secret'); ?></div>
	</div>
</div>


<h3 class="cm-settings-collapse-btn">
	<span class="dashicons dashicons-arrow-down"></span>
	<strong>Google+</strong>
</h3>
<p>Instructions are available here: <a href="​http://creativeminds.helpscoutdocs.com/article/990-cm-answers-cma-social-login-google">​http://creativeminds.helpscoutdocs.com/article/990-cm-answers-cma-social-login-google</a></p>
<p>Redirect URI: <?php echo site_url(); ?>/auth/google/oauth2callback</p>
<p>Authorized JavaScript origins: <?php echo site_url() ?></p>
<div class="cm-settings-collapse-container cm-settings-collapse-open">
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">Client ID:</div>
		<div class="cm-settings-control"><input type="text" size="60" name="google_client_id" value="<?php echo esc_attr($google_client_id); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('Google Client ID for web application'); ?></div>
	</div>
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">Client Secret:</div>
		<div class="cm-settings-control"><input type="text" size="60" name="google_client_secret" value="<?php echo esc_attr($google_client_secret); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('Google Client Secret'); ?></div>
	</div>
</div>

<h3 class="cm-settings-collapse-btn">
	<span class="dashicons dashicons-arrow-down"></span>
	<strong>LinkedIn</strong>
</h3>
<ul>
	<li><?php printf(CMA_Settings::__('Create LinkedIn application at %s'),
		'<a href="https://www.linkedin.com/secure/developer" target="new">https://www.linkedin.com/secure/developer</a>'); ?></li>
	<li><?php echo CMA_Settings::__('Enter your website url:'); ?> <?php bloginfo('url') ?></li>
	<li><?php echo CMA_Settings::__('There is no need to enter OAuth Redirect URL.'); ?></li>
	<li><?php echo CMA_Settings::__('Enable the <strong>r_emailaddress</strong> permission'); ?></li>
	<li><?php echo CMA_Settings::__('Go to JavaScript section and add the allowed domain:'); ?> http<?php echo (is_ssl() ? 's': '') .'://'. str_replace('www.', '', $_SERVER['HTTP_HOST']); ?></li>
</ul>
<?php if (!function_exists('curl_init')): ?>
	<p><?php echo CMA_Settings::__('Warning: the cURL functions are not available on this server. Contact your server administrator '
		. 'to enable support for cURL. Until that, login by this provider will be not available for users.'); ?></p>
<?php endif; ?>
<div class="cm-settings-collapse-container cm-settings-collapse-open">
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">API Key:</div>
		<div class="cm-settings-control"><input type="text" size="60" name="linkedin_api_key" value="<?php echo esc_attr($linkedin_api_key); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('LinkedIn API Key'); ?></div>
	</div>
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">Secret Key:</div>
		<div class="cm-settings-control"><input type="text" size="60" name="linkedin_secret_key" value="<?php echo esc_attr($linkedin_secret_key); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('LinkedIn Secret Key'); ?></div>
	</div>
</div>


<h3>Twitter</h3>
<ul>
	<li><?php printf(CMA_Settings::__('Create Twitter application at %s'),
		'<a href="https://dev.twitter.com/apps/" target="new">https://dev.twitter.com/apps/</a>'); ?></li>
	<li><?php echo CMA_Settings::__('Make sure that callback URL is set to:'); ?> <?php echo site_url(); ?>/auth/twitter/oauthcallback</li>
	<li><?php echo CMA_Settings::__('On settings tab check option "Allow this application to be used to Sign in with Twitter".'); ?></li>
</ul>
<?php if (!function_exists('curl_init')): ?>
	<p><?php echo CMA_Settings::__('Warning: the cURL functions are not available on this server. Contact your server administrator '
		. 'to enable support for cURL. Until that, login by this provider will be not available for users.'); ?></p>
<?php endif; ?>
<div class="cm-settings-collapse-container cm-settings-collapse-open">
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">Consumer key:</div>
		<div class="cm-settings-control"><input type="text" size="60" name="twitter_consumer_key" value="<?php echo esc_attr($twitter_consumer_key); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('Twitter Consumer Key'); ?></div>
	</div>
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">Consumer secret:</div>
		<div class="cm-settings-control"><input type="text" size="60" name="twitter_consumer_secret" value="<?php echo esc_attr($twitter_consumer_secret); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('Twitter Consumer Secret'); ?></div>
	</div>
</div>



<h3>Microsoft Live</h3>
<ul>
	<li><?php printf(CMA_Settings::__('Create Microsoft Live application at %s'),
		'<a href="https://account.live.com/developers/applications/index" target="new">https://account.live.com/developers/applications/index</a>'); ?></li>
	<li><?php echo CMA_Settings::__('Make sure that callback URL is set to:'); ?> <?php echo site_url(); ?>/auth/live/oauth2callback</li>
	<li><?php echo CMA_Settings::__('Choose option "No" for question of whether application is for mobile devices.'); ?></li>
</ul>
<div class="cm-settings-collapse-container cm-settings-collapse-open">
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">Client ID:</div>
		<div class="cm-settings-control"><input type="text" size="60" name="live_client_id" value="<?php echo esc_attr($live_client_id); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('Live Client ID'); ?></div>
	</div>
	<div class="cm-settings-row">
		<div class="cm-settings-option-name">Client Secret:</div>
		<div class="cm-settings-control"><input type="text" size="60" name="live_client_secret" value="<?php echo esc_attr($live_client_secret); ?>" /></div>
		<div class="cm-settings-desc"><?php echo CMA_Settings::__('Live Client Secret'); ?></div>
	</div>
</div>
