<div class="cma-contributor-page">

	<div class="cma-backlink-wrapper"><a class="cma-backlink" href="<?php echo esc_attr(CMA::getReferer()); ?>"> &laquo; <?php echo CMA_Labels::getLocalized('back_to_previous_page'); ?></a></div>
	
	<?php if ($user = CMA_User::getInstance($user_id)): ?>

		<h2><?php echo apply_filters('cma_contributor_header', $user->display_name, $user); ?></h2>
		<?php if ($avatar = $user->getAvatarHtml()): ?>
			<a id="cma-user-gravatar" class="cma-user-gravatar"><?php echo $avatar; ?></a>
		<?php endif; ?>
		
		<?php if( !empty($socialLinks) ): ?>
		    <h2><?php _e('Social Profiles', 'cm-answers-pro'); ?>:</h2>
		    <?php
		    foreach($socialLinks as $provider => $link)
		    {
		        $providerimage = CMA_RESOURCE_URL . '/imgs/s_' . $provider . '.png';
		        ?>
		        <a href="<?php echo esc_attr($link); ?>" target="_blank" rel="nofollow"><img src="<?php echo esc_attr($providerimage);
		        	?>" alt="<?php echo esc_attr(ucfirst($provider)) ?>" /></a>
		        <?php
		    }
		    ?>
		<?php endif; ?>
		
		
		<?php if (!CMA_Thread::showOnlyOwnQuestions() OR $user_id == get_current_user_id()): ?>
			
			<h2><?php echo CMA_Labels::getLocalized('Questions'); ?>:</h2>
			<?php
			$public = true;
			
			$displayOptions = array_merge(CMA_Settings::getDisplayOptionsDefaults(), array(
			    'hideQuestions' => 0,
			    'tags'          => 0,
			    'pagination'    => 0,
			    'form'          => 0,
			    'categories'    => 0,
			    'search'        => 0,
			    'views'         => 1,
			    'votes'         => 1,
			    'answers'       => 1,
				'navbar'        => 0,
				'sortbar'       => 0,
			));
			
		// 	echo CMA_BaseController::_loadView('answer/widget/questions', compact('questions', 'public', 'displayOptions'));
			
			echo do_shortcode(sprintf('[cma-questions author=%d form=0 search=0 sort=newest pagination=1 navbar=0 displaycategories=1 views=1 sortbar=0 limit=10]', $user->ID));
			
			?>
			
			<div class="cma-answers-list">
			    <h2><?php echo CMA_Labels::getLocalized('Answers'); ?>:</h2>
			    <?php echo do_shortcode(sprintf('[cma-answers author=%d limit=10 ajax=1]', $user->ID)); ?>
			</div>
			
		<?php endif; ?>
		
		<?php do_action('cma_referral_link'); ?>
		
	<?php endif; ?>

</div>