<?php

CMA_ContributorController::get_header();
$sidebarEnabled = (CMA_Settings::getOption(CMA_Settings::OPTION_SIDEBAR_ENABLED)
	AND is_active_sidebar('cm-answers-sidebar')
	AND CMA_Settings::getOption(CMA_Settings::OPTION_SIDEBAR_CONTRIBUTOR_ENABLED));

?>

<div id="primary" class="content-area cma-content<?php echo ($sidebarEnabled ? ' cma-col-left' : ' full-width'); ?>">
    <div id="content" role="main" class="site-content">
    	<div class="cma-main">
    		<div class="cma-wrapper page type-page hentry">
    			<div class="entry-content">
	                <?php the_content() ?>
	                <?php do_action('cma_referral_link'); ?>
	                <div class="cma-clear"></div>
	            </div>
            </div>
        </div>
    </div>
</div>
<?php
/*
 * CMA-Sidebar
 */
if($sidebarEnabled) echo CMA_BaseController::_loadView('answer/widget/sidebar');
?>
<?php
get_footer();
