<?php
$labelsByCategories = CMPD_Labels::getLabelsByCategories();

foreach ( $labelsByCategories as $category => $labels ):
	?>
	<table>
		<caption><?php echo esc_html( empty( $category ) ? 'Other' : $category  ); ?></caption>
		<?php
		foreach ( $labels as $key ):
			$defaultArr = array( 'product_name' => 'Product Name', 'product_pitch' => 'Product Pitch' );
			if ( array_key_exists( $key, $defaultArr ) ) {
				$default = $defaultArr[ $key ];
			} else {
				$default = CMPD_Labels::getDefaultLabel( $key );
			}
			if ( $default ) :
				?>
				<tr valign="top">
					<th scope="row" valign="middle" align="left" >"<?php echo esc_html( $default ) ?>" label:</th>
					<td>
						<input type="text" size="60" name="label_<?php echo esc_attr( $key ); ?>" value="<?php echo esc_attr( CMPD_Labels::getLabel( $key ) ); ?>" placeholder="<?php echo esc_attr( $default ) ?>"/>
					</td>
					<td><?php echo CMPD_Labels::getDescription( $key ); ?></td>
				</tr>
			<?php endif; ?>
		<?php endforeach; ?>
	</table>
<?php endforeach; ?>